### ISSUE TITLE
Tests failing on Python 2

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/pubtools-pulplib#21]
There are two test cases that random fails on Python 2.7.

```python
========================= FAILURES ==========================
_________________ test_search_can_paginate __________________

client = <tests.conftest.FastRetryClient object at 0x7fb1bf4b8890>, requests_mocker = <requests_mock.mocker.Mocker object at 0x7fb1bf50d290>

    def test_search_can_paginate(client, requests_mocker):
        """Paginated search will stop issuing requests if pages are no longer referenced."""
    
        client._PAGE_SIZE = 10
    
        expected_repos = []
        responses = []
        current_response = []
        for i in range(0, 997):
            repo_id = "repo-%s" % i
            expected_repos.append(Repository(id=repo_id))
            current_response.append({"id": repo_id})
            if len(current_response) == client._PAGE_SIZE:
                responses.append({"json": current_response})
                current_response = []
    
        responses.append({"json": current_response})
    
        requests_mocker.post(
            "https://pulp.example.com/pulp/api/v2/repositories/search/", responses
        )
    
        # Imagine we have some function which processes two pages of results and
        # then stops
        def do_something_first_two_pages(repos_f):
            page = repos_f.result()
            return len(page.data) + len(page.next.result().data)
    
        two_pages_len = do_something_first_two_pages(client.search_repository())
    
        # It should have seen the first two pages
        assert two_pages_len == 20
    
        # Now wait a bit to ensure any futures under the hood have time to finish up
        time.sleep(2.0)
    
        # It should have done only two or three requests
        # (2 vs 3 depends on scheduling). Because we threw away all references to
        # the search result, it stopped searching rather than continuing through
        # all pages.
>       assert requests_mocker.call_count in (2, 3)
E       assert 43 in (2, 3)
E        +  where 43 = <requests_mock.mocker.Mocker object at 0x7fb1bf50d290>.call_count

tests/client/test_search_stops.py:45: AssertionError
____________________ test_publish_cancel ____________________

fast_poller = None, requests_mocker = <requests_mock.mocker.Mocker object at 0x7fb1bfff13d0>, client = <tests.conftest.FastRetryClient object at 0x7fb1bf65c550>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fb1bc6bc790>

    def test_publish_cancel(fast_poller, requests_mocker, client, caplog):
        """Cancelling a publish future will cancel running Pulp task(s)."""
    
        repo = YumRepository(
            id="some-repo",
            distributors=(
                Distributor(id="yum_distributor", type_id="yum_distributor"),
                Distributor(id="cdn_distributor", type_id="cdn_distributor"),
            ),
        )
        repo.__dict__["_client"] = client
    
        requests_mocker.post(
            "https://pulp.example.com/pulp/api/v2/repositories/some-repo/actions/publish/",
            [{"json": {"spawned_tasks": [{"task_id": "task1"}]}}],
        )
    
        task_search_url = "https://pulp.example.com/pulp/api/v2/tasks/search/"
        requests_mocker.post(
            task_search_url, [{"json": [{"task_id": "task1", "state": "running"}]}]
        )
    
        requests_mocker.delete("https://pulp.example.com/pulp/api/v2/tasks/task1/")
    
        # Start the publish
        publish_f = repo.publish()
    
        # Wait until we're sure poll thread has seen this task
        for _ in range(0, 1000):
            if (
                requests_mocker.last_request
                and requests_mocker.last_request.url == task_search_url
            ):
                break
            time.sleep(0.001)
        assert requests_mocker.last_request.url == task_search_url
    
        # We should be able to cancel it
        assert publish_f.cancel()
    
        # It should have cancelled the underlying Pulp task
        req = requests_mocker.last_request
>       assert req.url == "https://pulp.example.com/pulp/api/v2/tasks/task1/"
E       AssertionError: assert 'https://pulp...tasks/search/' == 'https://pulp..../tasks/task1/'
E         - https://pulp.example.com/pulp/api/v2/tasks/search/
E         ?                                             ^^^^^
E         + https://pulp.example.com/pulp/api/v2/tasks/task1/
E         ?   
```

These tests do not fail every single time, they usually fail if you run twice or more.

I'm using `tox -e py27` to run tests, the same way that Travis CI does and it also fails on Travis as shown in PR #20.

**Comment by alexandrevicenzi** [comment]
I'm not sure what is the problem, but there are different packages being used, and maybe the issue could be somewhere else.

[Here](http://www.mergely.com/kAhWcMoR/) is the diff of package versions in both python versions.

**Comment by rohanpm** [comment]
There was a PR merged for this, but I'm reopening because there's still a failure in one of the modified tests:

https://travis-ci.org/release-engineering/pubtools-pulplib/jobs/550560983

```
=================================== FAILURES ===================================
__________________________ test_search_stops_paginate __________________________
requests_mocker = <requests_mock.mocker.Mocker object at 0x7f32eaefcef0>
    def test_search_stops_paginate(requests_mocker):
        """Paginated search will stop issuing requests if pages are no longer referenced."""
    
        client = Client("https://pulp.example.com/")
        client._PAGE_SIZE = 10
    
        responses = []
        current_response = []
        for i in range(0, 997):
            repo_id = "repo-%s" % i
            current_response.append({"id": repo_id})
            if len(current_response) == client._PAGE_SIZE:
                responses.append({"json": current_response})
                current_response = []
    
        responses.append({"json": current_response})
    
        # Inject a failing response for stable behavior from test:
        #
        # The expected behavior is that, after the first two requests,
        # pagination is cancelled since we no longer hold onto a page.
        # But that cancellation is racing with the scheduling of the
        # request, and there is generally no way to ensure our cancel
        # happens before the request thread starts the request, so we
        # can't be sure about how many requests we'd do.
        #
        # However, if we insert a failure after the first two pages,
        # then the client will need to retry a request (with some delay).
        # It should always be possible to cancel the request during that
        # retry delay, making the test stable.
        responses.insert(2, {"status_code": 500})
    
        requests_mocker.post(
            "https://pulp.example.com/pulp/api/v2/repositories/search/", responses
        )
    
        # Imagine we have some function which processes two pages of results and
        # then stops
        def do_something_first_two_pages(repos_f):
            page = repos_f.result()
            return len(page.data) + len(page.next.result().data)
    
        two_pages_len = do_something_first_two_pages(client.search_repository())
    
        # It should have seen the first two pages
        assert two_pages_len == 20
    
        # Now wait a bit to ensure any futures under the hood have time to finish up
        time.sleep(2.0)
    
        # It should have done only two or three requests
        # (2 vs 3 depends on scheduling). Because we threw away all references to
        # the search result, it stopped searching rather than continuing through
        # all pages.
>       assert requests_mocker.call_count in (2, 3)
E       assert 4 in (2, 3)
E        +  where 4 = <requests_mock.mocker.Mocker object at 0x7f32eaefcef0>.call_count
tests/client/test_search_stops.py:59: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  pubtools.pulplib:retry.py:50 Retrying due to error: 500 Server Error: None for url: https://pulp.example.com/pulp/api/v2/repositories/search/ [1/10]
                                      Traceback (most recent call last):
                                        File "/home/travis/build/release-engineering/pubtools-pulplib/pubtools/pulplib/_impl/client/client.py", line 214, in _unpack_response
                                          parsed = pulp_response.json()
                                        File "/home/travis/build/release-engineering/pubtools-pulplib/.tox/cov-travis/lib/python3.6/site-packages/requests/models.py", line 897, in json
                                          return complexjson.loads(self.text, **kwargs)
                                        File "/opt/python/3.6.3/lib/python3.6/json/__init__.py", line 354, in loads
                                          return _default_decoder.decode(s)
                                        File "/opt/python/3.6.3/lib/python3.6/json/decoder.py", line 339, in decode
                                          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                        File "/opt/python/3.6.3/lib/python3.6/json/decoder.py", line 357, in raw_decode
                                          raise JSONDecodeError("Expecting value", s, err.value) from None
                                      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                      
                                      During handling of the above exception, another exception occurred:
                                      
                                      Traceback (most recent call last):
                                        File "/home/travis/build/release-engineering/pubtools-pulplib/.tox/cov-travis/lib/python3.6/site-packages/more_executors/_impl/map.py", line 36, in _delegate_resolved
                                          result = self._map_fn(result)
                                        File "/home/travis/build/release-engineering/pubtools-pulplib/pubtools/pulplib/_impl/client/client.py", line 219, in _unpack_response
                                          pulp_response.raise_for_status()
                                        File "/home/travis/build/release-engineering/pubtools-pulplib/.tox/cov-travis/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
                                          raise HTTPError(http_error_msg, response=self)
                                      requests.exceptions.HTTPError: 500 Server Error: None for url: https://pulp.example.com/pulp/api/v2/repositories/search/
----------- coverage: platform linux, python 3.6.3-final-0 -----------
Name                                                   Stmts   Miss  Cover
--------------------------------------------------------------------------
pubtools/__init__.py                                       0      0   100%
pubtools/pulplib/__init__.py                               5      0   100%
pubtools/pulplib/_impl/__init__.py                         0      0   100%
pubtools/pulplib/_impl/client/__init__.py                  2      0   100%
pubtools/pulplib/_impl/client/client.py                  111      0   100%
pubtools/pulplib/_impl/client/errors.py                    7      0   100%
pubtools/pulplib/_impl/client/poller.py                  116      0   100%
pubtools/pulplib/_impl/client/retry.py                    31      0   100%
pubtools/pulplib/_impl/client/search.py                   19      0   100%
pubtools/pulplib/_impl/compat_attr.py                     11      0   100%
pubtools/pulplib/_impl/criteria.py                        41      0   100%
pubtools/pulplib/_impl/fake/__init__.py                    1      0   100%
pubtools/pulplib/_impl/fake/client.py                     81      0   100%
pubtools/pulplib/_impl/fake/controller.py                 11      0   100%
pubtools/pulplib/_impl/fake/match.py                      62      0   100%
pubtools/pulplib/_impl/model/__init__.py                   4      0   100%
pubtools/pulplib/_impl/model/attr.py                      11      0   100%
pubtools/pulplib/_impl/model/common.py                    32      0   100%
pubtools/pulplib/_impl/model/convert.py                   14      0   100%
pubtools/pulplib/_impl/model/distributor.py               13      0   100%
pubtools/pulplib/_impl/model/repository/__init__.py        4      0   100%
pubtools/pulplib/_impl/model/repository/base.py           92      0   100%
pubtools/pulplib/_impl/model/repository/container.py      15      0   100%
pubtools/pulplib/_impl/model/repository/file.py            9      0   100%
pubtools/pulplib/_impl/model/repository/yum.py             8      0   100%
pubtools/pulplib/_impl/model/task.py                      65      0   100%
pubtools/pulplib/_impl/page.py                            24      0   100%
pubtools/pulplib/_impl/schema/__init__.py                 12      0   100%
pubtools/pulplib/_impl/util.py                            11      0   100%
--------------------------------------------------------------------------
TOTAL                                                    812      0   100%
===================== 1 failed, 81 passed in 5.92 seconds ======================
```

**Comment by rohanpm** [comment]
I think the remaining failure would probably be fixed by https://github.com/rohanpm/more-executors/issues/150, so I'm planning to review the state after there's a fix available for that.
